name: Deploy JSON Server to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d3ut6nre5dus739ucdug?key=hyz4PrWvFHI"
